{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "52b6313a-621f-4e6d-9061-50c723a04476-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名错误', 'username': '财友', 'password': '654321', 'error_msg': '账号或密码错误'}"}], "start": 1614176057291, "stop": 1614176061000, "uuid": "c26adb33-c113-432f-adad-a4c6de8eeead", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "2540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}